### ISSUE TITLE
Is this still working?

### ISSUE THREAD

**Issue by irqstorm** [rschlaikjer/hello-stm32-1-usart#1]
Hey, following your tutorial, with the black magic probe and your EAGLE designs.

Compilation works perfectly fine, but the serial output doesn't seem to work. If you have the availability could you try if this still works? Maybe firmware updates to the probe broke it.

The screen session remains completely empty when running, even though the LED is blinking.

**Comment by rschlaikjer** [comment]
Hi,
I'd expect this to still work - if you have an oscilloscope, can you verify if there is any activity at all on the UART TX pin? There may be a short, cold joint or other mechanical problem. 

Also make sure that
- You do not have the TX and RX connections swapped to the black magic probe
- You have configured the probe with the correct baudrate
- The voltage sense / ground lines of the probe are also connected. The probe has level shifters that need a power reference from the target (unless you are using the black magic probe to supply power using `mon tpwr en`)

If you have inspected the pin and do not see a problem, and still do not see anything on the scope, then I would start to dig into the register values for the uart and see if they differ. Let me know if you can't find any simpler solution and we can try to work through it.

**Comment by irqstorm** [comment]
Thanks for the fast reply, I'll check and return with a reply.

**Comment by irqstorm** [comment]
I'm ashamed 😰

<img width="287" alt="Screenshot 2020-05-20 at 21 57 32" src="https://user-images.githubusercontent.com/7121006/82486019-f0b77f80-9ae4-11ea-8127-5a403aa3aac1.png">

The RX/TX lines were swapped, spent the whole day debugging it, it's always the simple things. Thanks for your time and the tutorials, great stuff!

**Comment by rschlaikjer** [comment]
Even professionals make these mistakes! Glad you're finding the tutorial useful.
